-- Adds the table required by the existing ContactMessage JPA entity.
-- CREATE TABLE IF NOT EXISTS is safe to rerun and does not alter or remove
-- any existing application data.

BEGIN;

CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;

-- Post-migration verification: this must return public.contact_messages.
SELECT to_regclass('public.contact_messages') AS contact_messages_table;
